### ISSUE TITLE
Add internal measurement information to the profiler plugin.

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#112]
With the future refactoring that I am planning on doing for the next few releases it would be very useful to have some kind of internal measurement. Would measure speed and some basic things. It would be similar to the statistics plugin except that it is keeping statistics on internal agent things.

Implementation wise, I think a global statistics counter can work. Then when the profiler plugin goes to generate the ZIP it can just dump those statistics to an entry.

**Comment by pselle** [comment]
Closing pending prioritization
