### ISSUE TITLE
Fork IOpipeExecution into an actual working class and no-op class to prevent NPE

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#140]
One might want to access `IOpipeExecution` outside of a valid wrapped method, for example if one uses a generic wrapper and then calls the method being wrapped then there is no execution available and as such `IOpipeExecution.instance()` returns `null`. This can cause a `NullPointerException` if they do not check for null and it would also require a bunch of code around cases where they want to use IOpipe features in specific areas. So the need to more freely use the `IOpipeExecution` instance that is returned without needing checks would make the code easier to read.

This would be seen if one manually wraps IOpipe and obtains a the `IOpipeExecution` instance, but does not call the entry point for IOpipe but the method that should be wrapped.

**Comment by pselle** [comment]
@XerTheSquirrel Can you clarify this issue, if this is an actual bug or a desired enhancement?
