### ISSUE TITLE
The trace plugin should not be an actual plugin

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#143]
The tracing plugin uses performance entries and creation of those performance entries is performed by a single class `TraceMeasurement` which can be obtained via `TraceExecution`. Measuring the amount of time something takes is quite fundamental to the library and it really should be something that is accessible from `IOpipeExecution` and not through secondary classes which eventually go through to `IOpipeExecution` anyway. The useful logic of the trace plugin is only about 35 lines of code so keeping it contained in a plugin adds complexity and makes it more confusing to maintain and use. Something this tiny should not be in its own standalone plugin.

**Comment by pselle** [comment]
Closing this and #149, as they seem unnecessary walks away from the general agent architecture in the other agents.
