### ISSUE TITLE
Event-info should not be an external plugin

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#149]
Event-info is currently a plugin which means it has the initialization and overhead that is added by plugins. It also is a plugin which is always enabled so it should not be standalone and treated as such when it is included anyway.

Blocked by #148.

**Comment by pselle** [comment]
Event-info is a plugin in other runtimes, why wouldn't it be in Java?

**Comment by XerTheSquirrel** [comment]
I believe that it is silly to have it included as a modular plugin which is brought in when it could be a part of the agent itself and integrated more tightly, it just heavily feels like needless modularization. Basically if there is a module that is almost in all cases always used, it should be part of the base code itself instead of tucked away in another place.

Of course, it could still be disabled.

At least from a Java perspective it just feels like it was a plugin because we can make it a plugin and for no other reason. There has been quite the push back in Java over doing things just because they are there, in this case using the plugin subsystem because it exists and why not make it a plugin.

**Comment by pselle** [comment]
@XerTheSquirrel Do we know the overhead of it being a plugin versus not? Are there significant gains to be made from changing how it works now?

**Comment by XerTheSquirrel** [comment]
The gains would be:
 * Less overhead because it would be one less plugin to go through and initialize.
 * Less code because we no longer need auxiliary classes and services to represent the plugin.

The speed that should be gained from it is negligible, but it should increase code maintainability.

**Comment by pselle** [comment]
Closing this and #143, as they seem unnecessary walks away from the general agent architecture in the other agents.
