### ISSUE TITLE
Use GitHub Pages for JavaDoc

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#22]
I think what would be really nice would be if the JavaDoc were to be placed in GitHub Pages stored in the repository as its own branch (rather than as `/docs` because an automated script would be quite bothersome and mess with merging so much). That way all the documentation is available and can be browsed. There is no need to worry about formatting much as JavaDoc outputs HTML and such. As a sample the documentation pretty much looks like this: <https://docs.oracle.com/javase/8/docs/api/>.

**Comment by pselle** [comment]
Published the output of `mvn javadoc:javadoc` here for a first pass: https://iopipe.github.io/iopipe-java/
