### ISSUE TITLE
Readme/documentation audit

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-java#23]
General issue for a docs run through by @nodebotanist, is complete when they close it :)

**Comment by nodebotanist** [comment]
Working through the lost of what's written. Should have an updated estimate tomorrow

**Comment by XerTheSquirrel** [comment]
If you have any questions on anything, would be happy to answer them!

**Comment by pselle** [comment]
Closing as a stale issue, will be more specific in future issues
