### ISSUE TITLE
Add .label option

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-java#41]
Allow users to "label" invocations (send a custom metric with only a name). This data goes into the labels array.

**Comment by XerTheSquirrel** [comment]
Would this be something like an environment variable which specifies extra custom metrics to use?

**Comment by pselle** [comment]
@XerTheSquirrel It's more syntactic sugar -- there's an open PR in Python https://github.com/iopipe/iopipe-python/pull/169 showing what that looks like there. The goal is to allow users to "tag" an invocation at run time, which is essentially a custom metric with only a name that either exists or not exists (ex. "sale-incomplete" might be something a user would add to an invocation in an e-commerce context)

**Comment by XerTheSquirrel** [comment]
Adding a custom metric with no value would be quite simple as there would only need a few changes to `IOpipeMeasurement` and `CustomMetric`.

**Comment by XerTheSquirrel** [comment]
Well thinking about it, adding new constructors to `CustomMetric` might be a bit confusing and could potentially cause some issues in the future. So I think the best thing to do would be to just add new methods in `IOpipeMeasurement` since tags only have a key that is "name".

**Comment by pselle** [comment]
Update: As this progressed, send labels in a `labels` section of the report (edited original issue to reflect). @XerTheSquirrel You have the go ahead to work on this!
