### ISSUE TITLE
Event-info plugin

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-java#50]
Plugin that translates events that we know about (ex. API gateway) into data for IOpipe to elevate to consumers. Python implementation for reference: https://github.com/iopipe/iopipe-python/tree/master/iopipe/contrib/eventinfo, and some overview of the feature: https://read.iopipe.com/serverless-observability-with-iopipe-event-sources-807c0cd64543

**Comment by XerTheSquirrel** [comment]
This is being worked on in #53.
