### ISSUE TITLE
Convert memory metrics to bytes

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-java#56]
Related: https://github.com/iopipe/iopipe-python/pull/198

The following should be in bytes to be consistent with the node agent:

* os.environment.totalmem
* os.environment.usedmem
* os.environment.freemem

Other metrics can remain as is for now.

**Comment by XerTheSquirrel** [comment]
I created pull request #59 for this issue.

**Comment by XerTheSquirrel** [comment]
This is fixed in #59.
