### ISSUE TITLE
Possibility of having an overhead counter in the report?

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#70]
There is some overhead to the Java agent and I would like a way to record the overhead in a report. Something that is at the top-level in the JSON. This would help in having a value that is a bit closer to the execution time Amazon reports especially during the initial cold start where it will be much longer.

Basically implementation wise it would count a timer from the earliest possible instant (at the entry of the service call) to the latest possible time (just before the JSON finishes generation).

**Comment by pselle** [comment]
You can't measure the time before the IOpipe library was loaded, which would be the full "overhead." We've discussed this in the past (and a few options on how to do it), and decided not to implement this at the agent level because it wouldn't close the gap truly.

**Comment by XerTheSquirrel** [comment]
Okay! This makes sense, I will close this issue then.
