### ISSUE TITLE
Collect disk usage

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-java#72]
The Java agent should collect usage for the `/tmp` directory. AWS Lambda allows the handler to write to `/tmp`.

For an example of collecting disk usage for `/tmp`:
https://github.com/iopipe/iopipe-python/blob/master/iopipe/system.py#L20

**Comment by kolanos** [comment]
Here's where disk usage appears in the report schema:
https://github.com/iopipe/iopipe-js-core/blob/master/src/schema.json#L20

**Comment by XerTheSquirrel** [comment]
This should be rather simple to implement as Java itself has a means to gather information about the filesystem. I can work on this tomorrow.
