### ISSUE TITLE
Write Tutorial Documentation on optimizing lambdas.

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#85]
After refactoring the profiler and such, write up a tutorial on using the profiler to optimize your code along with a bunch of things that can be done to make it better. Additionally include some examples which use progressively better code as part of the tutorial.

This should be done after #75, #77, #82, #84 as all of those will make the profiler snapshots and statistics more sane to base information from.

**Comment by pselle** [comment]
Is this still blocked?

**Comment by XerTheSquirrel** [comment]
@pselle This is no longer blocked.

**Comment by XerTheSquirrel** [comment]
This has been moved to https://github.com/iopipe/Content/issues/56.
