### ISSUE TITLE
Auto Labels

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-java#86]
Labels should be automatically added to invocations based on agent usage.

See: https://github.com/iopipe/launchpad/issues/46

**Comment by XerTheSquirrel** [comment]
Blocked by #97, since there will need to be so many new labels to be tested the way the current code is, it will just be a giant mess testing it.

**Comment by XerTheSquirrel** [comment]
Waiting for #97, but I can work on this and rebase whatever changes happen since there should be no conflicts at all.

**Comment by XerTheSquirrel** [comment]
Working on this in #108 .
