### ISSUE TITLE
Support SQS with Event-info

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-java#89]
It's newly released trigger type is now available: https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/doc_source/eventsources.md#eventsources-sqs

**Comment by XerTheSquirrel** [comment]
With an initial quick look, SQS events are not in <https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events> and there is <https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/java/example_code/sqs/src/main/java/aws/example/sqs> but that is client side only. Will have to do some research to see how SQS will be handled and if they even have SQS on the Java server end yet.

**Comment by adjohn** [comment]
Oops looks like they removed the document for SQS as it isn't quite released officially yet.  Here's the old doc for it though: https://github.com/awsdocs/aws-lambda-developer-guide/commit/c7010555746e87c4b1480590212e6be6f860f072#diff-dfb4e406da4248d910c31e091e1424a9a
