### ISSUE TITLE
Improve the release process for Java

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-java#90]
Okay! So we definitely need to improve and simplify the release process. Me and @pselle have been discussing this on Slack and I definitely feel that we both feel that the release process is too complicated. Some of the bad points:

 * Before the release we have to update the JavaDocs/Site and correct `IOpipeConstants`.
 * It is not automatic and requires that we run a script to release locally and with the proper environment variables.
 * The build had failed today and it created a tag which required CircleCI to clear the repository cache so CircleCI no longer saw that tag, we also were not able to release a different version because we _have_ to release our SNAPSHOT version.

Ideally the best solution would be one of these:

 1. Tag the release where the build system picks that up and performs a release from it.
 2. Modify a single file or similar which the build system picks up and performs a release from it.

It should be done to make it work on CircleCI 2.0 since 1.0 is very soon near end of life (there is issue #38).

If a release cannot be made then it should back off and not try to modify repository again and push anything that cannot be reverted. Cancelled or failed releases should not cause the repository to get stuck like it did before with the tag issue.

I think for safety if we can, we can clone the repository to a temporary directory and perform the release work there if we make any commits. Then if the release worked then push the commits to master so that way the cached repository does not get messed up, it should check out hopefully. Maybe if there are multiple commits that would be made, maybe we can just have them squashed into a single commit.

I think one thing we can do automatically is that perhaps we can split off the JavaDocs and instead put that into another repository or a non-repository location (iopipe.com?). Essentially have a hook that when there is a new commit to master it runs the JavaDoc and site build and stores that. That way we do not need to run commits and the JavaDoc would always be up to date on master. If we want to go a step further the script could also mirror tags in the main repository for releases if that is important anyway. At least then we would not have to worry about running the JavaDoc ever and having that complicate pulling and the release process.

This message is already pretty long so I will put this down for now and add another reply following this.

**Comment by XerTheSquirrel** [comment]
Okay for this, I definitely want to split off the Maven Site/JavaDoc and move it into another repository.

**Comment by XerTheSquirrel** [comment]
Well, the JavaDocs clutter the repository and they are only updated before every release so they are quite static. It is nice to have the JavaDocs available but they should not be in this repository.

The optimal solution would for them to be at say: <https://iopipe.com/javadoc>, which would be updated per release.

But I am all for dropping the docs from the repository.

**Comment by pselle** [comment]
Ok, we can drop them if they're making Circle 2.0/release improvements complicated. They're still of course, user-generatable

**Comment by XerTheSquirrel** [comment]
The Java release process could be further improved by having a setup where we only need to tag a release in GitHib. For now CircleCI 2.0 support is going to be pushed in so that way it is there because we do have a deadline on it.

See:
 * https://github.com/iopipe/iopipe-java/pull/92#issuecomment-402829699
 * https://github.com/iopipe/iopipe-java/pull/92#issuecomment-402845835
 * https://github.com/iopipe/iopipe-java/pull/92#issuecomment-403853778
 * https://github.com/iopipe/iopipe-java/pull/92#issuecomment-403953074

**Comment by XerTheSquirrel** [comment]
Moved this to Release 1.9.0, for the logging plugin going to take up the opportunity to get this done for a small project (a logger plugin plugin), then when it works adapt it to this repository.

**Comment by XerTheSquirrel** [comment]
Moved this to the 1.10.0 release since there will not be enough time for this and it is too risky to hold off on a release when it is ready to go out.

**Comment by XerTheSquirrel** [comment]
Update, since working on the logger adapters I have figured out how to do this with the minimal set of changes. Apart from changing the code there needs to be a way to store the version number in a resource so that the constants can be read and reported to IOpipe accordingly for the correct agent version.
